# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scanner_pres.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scanner_pres.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12scanner_pres.proto\"5\n\x0bSiteWithCMS\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0b\n\x03\x63ms\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\"-\n\rVulnerability\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\"\xbe\x01\n\nScanResult\x12\x0f\n\x07scan_id\x18\x01 \x01(\t\x12\x12\n\ntarget_url\x18\x02 \x01(\t\x12\x10\n\x08\x63ms_type\x18\x03 \x01(\t\x12\x0c\n\x04mode\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\x12\x11\n\tscan_time\x18\x06 \x01(\x01\x12\x10\n\x08mongo_id\x18\x07 \x01(\t\x12\'\n\x0fvulnerabilities\x18\x08 \x03(\x0b\x32\x0e.Vulnerability\x12\r\n\x05\x65rror\x18\t \x01(\t\"]\n\x0cScanResponse\x12\x0f\n\x07scan_id\x18\x01 \x01(\t\x12\x10\n\x08\x63ms_type\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x1c\n\x07results\x18\x04 \x03(\x0b\x32\x0b.ScanResult2g\n\x0eScannerService\x12(\n\tScanLight\x12\x0c.SiteWithCMS\x1a\r.ScanResponse\x12+\n\x0cScanComplete\x12\x0c.SiteWithCMS\x1a\r.ScanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scanner_pres_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SITEWITHCMS']._serialized_start=22
  _globals['_SITEWITHCMS']._serialized_end=75
  _globals['_VULNERABILITY']._serialized_start=77
  _globals['_VULNERABILITY']._serialized_end=122
  _globals['_SCANRESULT']._serialized_start=125
  _globals['_SCANRESULT']._serialized_end=315
  _globals['_SCANRESPONSE']._serialized_start=317
  _globals['_SCANRESPONSE']._serialized_end=410
  _globals['_SCANNERSERVICE']._serialized_start=412
  _globals['_SCANNERSERVICE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
